cmake_minimum_required(VERSION 3.25)

if(COREKIT_TARGET_PLATFORM STREQUAL "esp32" OR
   COREKIT_TARGET_PLATFORM STREQUAL "esp32s2" OR
   COREKIT_TARGET_PLATFORM STREQUAL "esp32s3" OR
   COREKIT_TARGET_PLATFORM STREQUAL "esp32c3" OR
   COREKIT_TARGET_PLATFORM STREQUAL "esp32c6")

    option(
        COREKIT_BUILD_PLATFORM_ESP32
        "Build ESP32 Platform"
        ON
    )

endif()