services:
  pixel-dev:
    container_name: pixel-dev

    build:
      context: ..
      dockerfile: ./.docker/common/base/Dockerfile

    privileged: true
    network_mode: host
    gpus: all
    tty: true
    stdin_open: true

    environment:
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: /tmp/runtime-root

    volumes:
      # Workspace
      - ..:/workspace:cached
      # Wayland socket
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/runtime-root/${WAYLAND_DISPLAY}
      # X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix

    tmpfs:
      - /tmp/runtime-root