services:
  corekit-base:
    image: corekit-base:latest
    build:
      context: .
      dockerfile: ./common/base/Dockerfile
      args:
        BASE_IMAGE: "ubuntu:24.04"

  corekit-tool-pico:
    image: corekit-tool-pico:latest
    depends_on:
      - corekit-base
    build:
      context: .
      dockerfile: platform/pico/Dockerfile
      args:
        BASE_IMAGE: corekit-base:latest
        ARM_BUILD_ARCH: x86_64
        ARM_TARGET_ARCH: arm-none-eabi
        ARM_TOOLCHAIN_VER: 15.3.rel1

  corekit-tool-posix:
    image: corekit-tool-posix:latest
    depends_on:
      - corekit-base
    build:
      context: .
      dockerfile: platform/posix/Dockerfile
      args:
        BASE_IMAGE: corekit-base:latest

  corekit-dev:
    image: corekit-dev:latest
    build:
      context: .
      dockerfile: ./common/dev/Dockerfile
      args:
        TOOLCHAIN_IMAGE: corekit-tool-${BUILD_PLATFORM}
    depends_on:
      - corekit-tool-${BUILD_PLATFORM}

    privileged: true
    network_mode: host
    gpus: all
    tty: true
    stdin_open: true

    environment:
      DISPLAY: ${DISPLAY}
      WAYLAND_DISPLAY: ${WAYLAND_DISPLAY}
      XDG_RUNTIME_DIR: /tmp/runtime-root

    volumes:
      # Workspace
      - ..:/workspace:cached
      # Wayland socket
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:/tmp/runtime-root/${WAYLAND_DISPLAY}
      # X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix

    tmpfs:
      - /tmp/runtime-root