cmake_minimum_required(VERSION 3.25)

set(CMAKE_C_STANDARD 17)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_POLICY_VERSION_MINIMUM 3.5)

if(NOT DEFINED COREKIT_BASE_OS)
    message(FATAL_ERROR "COREKIT_BASE_OS is not set")
    return()
endif()

if(NOT DEFINED COREKIT_BUILD_TEST)
    message(WARNING "COREKIT_BUILD_TEST is not set. Disabling tests.")
    option(COREKIT_BUILD_TEST "Build Tests" OFF)
endif()

if (COREKIT_BUILD_TEST)
    enable_testing()
endif()

set(COREKIT_WORKDIR ${CMAKE_CURRENT_SOURCE_DIR})
set(COREKIT_CMAKE_DIR "${COREKIT_WORKDIR}/cmake/${COREKIT_BASE_OS}")
set(COREKIT_BOOTSTRAP_FILE "${COREKIT_CMAKE_DIR}/bootstrap.cmake")
set(COREKIT_CONFIGURE_FILE "${COREKIT_CMAKE_DIR}/configure.cmake")

message(STATUS "COREKIT_BOOTSTRAP_FILE: ${COREKIT_BOOTSTRAP_FILE}")
message(STATUS "COREKIT_CONFIGURE_FILE: ${COREKIT_CONFIGURE_FILE}")
message(STATUS "COREKIT_BASE_OS: ${COREKIT_BASE_OS}")
message(STATUS "COREKIT_BUILD_TEST: ${COREKIT_BUILD_TEST}")